### ISSUE TITLE
Poller iteration gets interrupted if one of the ExternalSecrets is not properly formatted (e.g. absent secretsDescriptor.data element)

### ISSUE THREAD

**Issue by walcovanloon** [external-secrets/kubernetes-external-secrets#158]
https://github.com/godaddy/kubernetes-external-secrets/blob/72a4f6f420230825b8cd55e42949e8655b04ba6c/lib/backends/kv-backend.js#L67

Expected outcome: 
a validation error is logged by the daemon, but handling of external secrets continues.

Actual outcome:
poller gets interrupted, does not continue with the ExternalSecrets that follow the malformatted ExternalSecret

Stacktrace logged:

at SecretsManagerBackend._fetchSecretPropertyValues (/app/lib/backends/kv-backend.js:26:37)\n    at SecretsManagerBackend.getSecretManifestData (/app/lib/backends/kv-backend.js:68:45)\n    at Poller._createSecretManifest (/app/lib/poller.js:52:8)\n    at Poller._upsertKubernetesSecret (/app/lib/poller.js:89:39)\n    at Poller._poll (/app/lib/poller.js:75:18)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)","msg":"Cannot read property 'map' of undefined","v":1}

**Comment by moolen** [comment]
I can reproduce this problem. We should also think about validating the `External Secret` resource using [OpenAPI Validation](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation). 

/good-first-issue

**Comment by Flydiverny** [comment]
#208 has been merged and CRD validation will be available in next release, but I think we could probably still do some improvements on error handling and reporting of borked externalsecrets.

**Comment by walcovanloon** [comment]
great, thanks for the fix!

**Comment by moolen** [comment]
I think this is done (#208). Feel free to re-open or create a new issue for enhancements.
