### ISSUE TITLE
Pod stuck after ETIMEDOUT error

### ISSUE THREAD

**Issue by runningman84** [external-secrets/kubernetes-external-secrets#351]
We have discovered multiple times that the external-secrets pod got stuck. The last error messages where these:

```
{"level":50,"time":1587377647230,"pid":18,"hostname":"kube-external-secrets-kubernetes-external-secrets-d8489bbcmx892","errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"172.20.0.1","port":443,"msg":"failure while polling the secret example-mod-example/example-mod-app-laravel","stack":"Error: connect ETIMEDOUT 172.20.0.1:443\n at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)","type":"Error","v":1}
{"level":50,"time":1587377647228,"pid":18,"hostname":"kube-external-secrets-kubernetes-external-secrets-d8489bbcmx892","errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"172.20.0.1","port":443,"msg":"failure while polling the secret example-mod-selfservice/example-mod-selfservice-laravel","stack":"Error: connect ETIMEDOUT 172.20.0.1:443\n at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)","type":"Error","v":1}
{"level":50,"time":1587367885196,"pid":18,"hostname":"kube-external-secrets-kubernetes-external-secrets-d8489bbcmx892","message":null,"code":"ParameterNotFound","time":"2020-04-20T07:31:25.195Z","requestId":"1b430ddc-458a-44f7-b6d7-d08b1460dac5","statusCode":400,"retryable":false,"retryDelay":78.85242507033838,"msg":"failure while polling the secret example-mod-example/example-mod-example-laravel","stack":"ParameterNotFound: null\n at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/json.js:51:27)\n at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)\n at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)\n at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n at /app/node_modules/aws-sdk/lib/state_machine.js:26:10\n at Request.<anonymous> (/app/node_modules/aws-sdk/li/request.js:38:9)\n at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)\n at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)","type":"Error","v":1}
```

It would be better to just crash the process in this case. This would allow k8s to restart the pod.

In this example I just deleted the pod and the secrets were updating again...

**Comment by VinothChinnadurai** [comment]
Can somebody address this quickly as it blocks our deployments..

**Comment by Flydiverny** [comment]
@VinothChinnadurai PR's welcome :)
