### ISSUE TITLE
Timeout with 4.0.0 with GCP

### ISSUE THREAD

**Issue by Sytten** [external-secrets/kubernetes-external-secrets#397]
I tried updating our release to 4.0.0, but the poller only timeout when using GCP:
```
{"level":50,"time":1591212177575,"pid":17,"hostname":"external-secrets-7f58c4f74c-dlptb","code":4,"stack":"Error: Retry total timeout exceeded before any response was received\n    at repeat (/app/node_modules/google-gax/build/src/normalCalls/retries.js:65:31)\n    at Timeout._onTimeout (/app/node_modules/google-gax/build/src/normalCalls/retries.js:100:25)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)","type":"Error","msg":"failure while polling the secret default/XXXXXXX"}
{"level":30,"time":1591212177588,"pid":17,"hostname":"external-secrets-7f58c4f74c-dlptb","msg":"status update failed for externalsecret default/XXXXXXX, due to modification, new poller should start"}
{"level":50,"time":1591212182143,"pid":17,"hostname":"external-secrets-7f58c4f74c-dlptb","code":4,"stack":"Error: Retry total timeout exceeded before any response was received\n    at repeat (/app/node_modules/google-gax/build/src/normalCalls/retries.js:65:31)\n    at Timeout._onTimeout (/app/node_modules/google-gax/build/src/normalCalls/retries.js:100:25)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)","type":"Error","msg":"failure while polling the secret default/XXXXXXX"}
{"level":30,"time":1591212182161,"pid":17,"hostname":"external-secrets-7f58c4f74c-dlptb","msg":"status update failed for externalsecret default/XXXXXXX, due to modification, new poller should start"}
```

Not much has changed since so I don't know what to think of it.

I reverted back to 3.3.0 and it works fine. I made sure to remove the `value` property like it was mentioned in the CHANGELOG (although the README has not been updated).

**Comment by Sytten** [comment]
Not stale

**Comment by misurin** [comment]
I am having the same issue, tried both 6.1.0 and 6.4.0.

**Comment by max-lobur** [comment]
Not stale, having the same with AWS SSM
```
status update failed for externalsecret test/sample-app, due to modification
```
