### ISSUE TITLE
Ungraceful handling of ETIMEDOUT

### ISSUE THREAD

**Issue by EricHorst** [external-secrets/kubernetes-external-secrets#407]
Vault backend. KES daemon dies when encountering a timeout talking to Vault API. This lead to a Pod crash looping problem.

I don't know the exact cause of the occasional timeout we were having talking to the Vault server, it was intermittent. However, dying is a very ungraceful solution to the timeout of an API connection. Timeouts can happen for all sorts of reasons. When talking to a backend, it seems that logging the timeout and storing a failure status for the current operation would be much better than a panic exit. 

```
2020-06-13 07:05:39.538 PDT RequestError: Error: connect ETIMEDOUT 2x.x47.x2.1x6:443 at new RequestError (/app/node_modules/request-promise-core/lib/errors.js:14:15) at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:87:29) at Request.RPcallback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31) at self.callback (/app/node_modules/request/request.js:185:22) at Request.emit (events.js:310:20) at Request.EventEmitter.emit (domain.js:482:12) at Request.onRequestError (/app/node_modules/request/request.js:881:8) at ClientRequest.emit (events.js:310:20) at ClientRequest.EventEmitter.emit (domain.js:482:12) at TLSSocket.socketErrorListener (_http_client.js:426:9) {
2020-06-13 07:05:39.538 PDT name: 'RequestError',
2020-06-13 07:05:39.538 PDT message: 'Error: connect ETIMEDOUT 2x.x47.x2.1x6:443',
2020-06-13 07:05:39.538 PDT cause: Error: connect ETIMEDOUT 2x.x47.x2.1x6:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
2020-06-13 07:05:39.538 PDT errno: 'ETIMEDOUT',
2020-06-13 07:05:39.538 PDT code: 'ETIMEDOUT',
2020-06-13 07:05:39.538 PDT syscall: 'connect',
2020-06-13 07:05:39.538 PDT address: '2x.x47.x2.1x6',
2020-06-13 07:05:39.538 PDT port: 443
2020-06-13 07:05:39.538 PDT },
2020-06-13 07:05:39.538 PDT error: Error: connect ETIMEDOUT 2x.x47.x2.1x6:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
2020-06-13 07:05:39.538 PDT errno: 'ETIMEDOUT',
2020-06-13 07:05:39.538 PDT code: 'ETIMEDOUT',
2020-06-13 07:05:39.538 PDT syscall: 'connect',
2020-06-13 07:05:39.538 PDT address: '2x.x47.x2.1x6',
2020-06-13 07:05:39.538 PDT port: 443
2020-06-13 07:05:39.538 PDT },
2020-06-13 07:05:39.538 PDT options: {
2020-06-13 07:05:39.538 PDT json: true,
2020-06-13 07:05:39.538 PDT resolveWithFullResponse: true,
2020-06-13 07:05:39.538 PDT simple: false,
2020-06-13 07:05:39.538 PDT strictSSL: true,
2020-06-13 07:05:39.538 PDT method: 'POST',
2020-06-13 07:05:39.538 PDT path: '/auth/token/renew-self',
2020-06-13 07:05:39.538 PDT headers: { 'X-Vault-Token': 'redacted' },
2020-06-13 07:05:39.538 PDT uri: 'https://redacted/v1/auth/token/renew-self',
2020-06-13 07:05:39.538 PDT callback: [Function: RP$callback],
2020-06-13 07:05:39.538 PDT transform: undefined,
2020-06-13 07:05:39.538 PDT transform2xxOnly: false
2020-06-13 07:05:39.538 PDT },
2020-06-13 07:05:39.538 PDT response: undefined
2020-06-13 07:05:39.538 PDT }
2020-06-13 07:05:39.713 PDT npm info lifecycle kubernetes-external-secrets@3.3.0~start: Failed to exec start script
2020-06-13 07:05:39.715 PDT npm ERR! code ELIFECYCLE
2020-06-13 07:05:39.715 PDT npm ERR! errno 1
2020-06-13 07:05:39.808 PDT npm ERR! kubernetes-external-secrets@3.3.0 start: `./bin/daemon.js`
2020-06-13 07:05:39.808 PDT npm ERR! Exit status 1
2020-06-13 07:05:39.808 PDT npm ERR!
2020-06-13 07:05:39.808 PDT npm ERR! Failed at the kubernetes-external-secrets@3.3.0 start script.
2020-06-13 07:05:39.808 PDT npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-06-13 07:05:39.817 PDT npm timing npm Completed in 5080407ms
2020-06-13 07:05:39.818 PDT 
```

**Comment by 2mf** [comment]
I'm seeing the same thing after ETIMEOUT polling stops.
Version: 3.1.0 and 3.3.0


```2020-06-30T09:02:01.370169847Z {"level":50,"time":1593507721369,"pid":17,"hostname":"external-secrets-8568467bc5-sbtch","errors":[{"message":"request to https://login.microsoftonline.com/1234567-1234-1234-1234-123456789012/oauth2/v2.0/token
failed, reason: read ETIMEDOUT","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"},{"statusCode":400,"errorResponse":{"error":"invalid_request","errorDescription":"Identity not found"},"name":"AuthenticationError"}],"name":"AggregateAuth
enticationError","stack":"AggregateAuthenticationError: Authentication failed to complete due to the following errors:\n\nFetchError: request to https://login.microsoftonline.com/1234567-1234-1234-1234-123456789012/oauth2/v2.0/token failed,
reason: read ETIMEDOUT\n\nAuthenticationError: An error was returned while authenticating to Azure Active Directory (status code 400).\n\nMore details:\n\n{\n  \"error\": \"invalid_request\",\n  \"errorDescription\": \"Identity not found\"\n}
\n    at DefaultAzureCredential.<anonymous> (/app/node_modules/@azure/identity/dist/index.js:173:29)\n    at Generator.throw (<anonymous>)\n    at rejected (/app/node_modules/tslib/tslib.js:108:69)\n    at runMicrotasks (<anonymous>)\n    at 
processTicksAndRejections (internal/process/task_queues.js:97:5)","type":"Error","msg":"failure while polling the secret backend/hybris-license"}```

**Comment by 2mf** [comment]
Seems to be a duplicate of #351

**Comment by EricHorst** [comment]
> Seems to be a duplicate of #351

Issue #351 didn't very clearly highlight the timeout as the problem, just that the KES wasn't responding. I would say that the problem in that issue is slightly different, as the question is why it is unresponsive.

But more importantly, the proposed solution in #351 of crashing the process might be right if it is actually unresponsive but it is definitely not the right action in the general timeout case. If KES crashes every time it has an issue talking to Vault or any other backend, it would lead to crash looping on any intermittent connectivity issue and a lot of crash looping if the outage were long. The better solution in the timeout case is to be smart about it, log the problem, track failures in metrics and otherwise continue to try to re-establish the connection until it resolves.

**Comment by 2mf** [comment]
I'm not so used to NodeJS code but I've analyzed the code around the _poll function. 
It looks like any error occurring while getting the secret from any keyvault backend, is not handled at all.

**Comment by andy-v-h** [comment]
I am seeing a similar `ETIMEDOUT` issue, however it is when the KES pod is trying to connect to `kubernetes` default service.

example `msg`s are:

-  `failure while polling the secret foo`
- `failure while updating status for externalsecret ingress-nginx/bar`
 And the error message when it crash is 

````
{"level":50,"time":1594198996087,"pid":17,"hostname":"kubernetes-external-secrets-647fff4686-lv4z6","errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"100.64.0.1","port":443,"stack":"Error: connect ETIMEDOUT 100.64.0.1:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","type":"Error","msg":"failure while updating status for externalsecret baz"}
Error: connect ETIMEDOUT 100.64.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '100.64.0.1',
  port: 443
}
npm info lifecycle kubernetes-external-secrets@4.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-external-secrets@4.0.0 start: `./bin/daemon.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kubernetes-external-secrets@4.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 252338ms
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-07-08T09_03_16_101Z-debug.log
````

My backend is AWS SSM. This is the only pod I can see having this issue connecting to the `kubernetes` service.

**Comment by doctornkz** [comment]
Hello folks! Having the same issue with AWS SSM + EKS.
```
{"level":50,"time":1583542415300,"pid":18,"hostname":"kubernetes-external-secrets-798c4d546c-nc8jq","errno":"EHOSTUNREACH","code":"EHOSTUNREACH","syscall":"connect","address":"172.20.0.1","port":443,"msg":"failure while polling the secret argocd/okta","stack":"Error: connect EHOSTUNREACH 172.20.0.1:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)","type":"Error","v":1} 
```
I am pretty sure we have a problem after or inside `try/catch` wrapper:
here: https://github.com/godaddy/kubernetes-external-secrets/blob/master/lib/poller.js#L131
or 
here: https://github.com/godaddy/kubernetes-external-secrets/blob/master/lib/poller.js#L174

I am not JS developer, but I will try too debug that more precisely.

**Comment by thapakazi** [comment]
Stumble upon the same issue, config update on AWS SSM was not reflected at the moment due to this.

**Comment by mrobinson513** [comment]
We have also just encountered this with KES attempting to pull values from AWS SSM. It seems triggering a restart on the deployment resolved the situation for us. 

Version: 5.1.0
EKS: v1.16.12-eks-904af05

In our setup, we use the private API endpoint provided by EKS, with the public endpoint locked down. Not sure if that makes a difference to anyone.

**Comment by TonyLovesDevOps** [comment]
I too ran into a similar issue. We're using EKS and AWS Secrets Manager. The symptoms are that the external secrets pod chugs along happily for weeks/months, and then hits a timeout talking to the EKS API due to some transient issue. Once this happens the pod remains running but hangs and does nothing (i.e. no polling of secrets manager, no log messages after the one below):

`{"level":50,"time":1599011960901,"pid":19,"hostname":"kubernetes-external-secrets-dcd75956f-6rdl2","errno":"EHOSTUNREACH","code":"EHOSTUNREACH","syscall":"connect","address":"172.20.0.1","port":443,"stack":"Error: connect EHOSTUNREACH 172.20.0.1:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","type":"Error","msg":"failure while polling the secret foo/bar"}`

**Comment by 2mf** [comment]
This issue still persists

**Comment by andrewreineke** [comment]
Experiencing the same with EKS + SSM.  Transient error -> no more polling until pod is replaced.
