### ISSUE TITLE
Error: secret $secret_name is invalid

### ISSUE THREAD

**Issue by gvfnix** [external-secrets/kubernetes-external-secrets#492]
Hi. I have deployed kubernetes-external-secrets with IRSA.
Now when I create the ExternalSecret object, I see the error message in operator's log.

ExternalSecret:
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: sample-docker-config-json
  namespace: default
spec:
  backendType: systemManager
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - key: /uv/eks/sample-dockerconfigjson
      name: ".dockerconfigjson"
```

Log looks like this:
```
npm info it worked if it ends with ok
npm info using npm@6.14.5
npm info using node@v12.18.2
npm info lifecycle kubernetes-external-secrets@5.2.0~prestart: kubernetes-external-secrets@5.2.0
npm info lifecycle kubernetes-external-secrets@5.2.0~start: kubernetes-external-secrets@5.2.0

> kubernetes-external-secrets@5.2.0 start /app
> ./bin/daemon.js

{"level":30,"time":1601039622861,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"loading kube specs"}
{"level":30,"time":1601039622939,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"successfully loaded kube specs"}
{"level":30,"time":1601039622940,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"updating CRD"}
{"level":30,"time":1601039622940,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"Upserting custom resource externalsecrets.kubernetes-client.io"}
{"level":30,"time":1601039622984,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"successfully updated CRD"}
{"level":30,"time":1601039622986,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"starting app"}
{"level":20,"time":1601039622987,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"Starting watch stream"}
Fri, 25 Sep 2020 13:13:42 GMT kubernetes-client deprecated .getStream use .getObjectStream, see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md at lib/external-secret.js:40:10
{"level":30,"time":1601039622989,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"successfully started app"}
{"level":30,"time":1601039622989,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"MetricsServer listening on port 3001"}
{"level":20,"time":1601039622996,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"spinning up poller for default/sample-docker-config-json"}
{"level":30,"time":1601039622996,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"starting poller for default/sample-docker-config-json"}
{"level":20,"time":1601039623006,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"next poll for default/sample-docker-config-json in 32214 ms"}
{"level":30,"time":1601039655236,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"running poll on the secret default/sample-docker-config-json"}
{"level":30,"time":1601039655256,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"fetching secret property /uv/eks/sample-dockerconfigjson with role: pods role"}
{"level":30,"time":1601039656495,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"upserting secret default/sample-docker-config-json"}
{"level":50,"time":1601039656503,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","code":422,"statusCode":422,"stack":"Error: Secret \"sample-docker-config-json\" is invalid: data[.dockerconfigjson]: Invalid value: \"<secret contents redacted>\": invalid character 'e' looking for beginning of value\n    at /app/node_modules/kubernetes-client/backends/request/client.js:231:25\n    at Request._callback (/app/node_modules/kubernetes-client/backends/request/client.js:168:14)\n    at Request.self.callback (/app/node_modules/kubernetes-client/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:315:20)\n    at Request.EventEmitter.emit (domain.js:482:12)\n    at Request.<anonymous> (/app/node_modules/kubernetes-client/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:315:20)\n    at Request.EventEmitter.emit (domain.js:482:12)\n    at IncomingMessage.<anonymous> (/app/node_modules/kubernetes-client/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:421:28)","type":"Error","msg":"failure while polling the secret default/sample-docker-config-json"}
{"level":20,"time":1601039656504,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"updating status for default/sample-docker-config-json to: ERROR, Secret \"sample-docker-config-json\" is invalid: data[.dockerconfigjson]: Invalid value: \"<secret contents redacted>\": invalid character 'e' looking for beginning of value"}
{"level":20,"time":1601039656520,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"stopping and removing poller 16ff9af3-337d-4257-9581-a4fedc357004"}
{"level":30,"time":1601039656521,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"stopping poller for default/sample-docker-config-json"}
{"level":20,"time":1601039656521,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"spinning up poller for default/sample-docker-config-json"}
{"level":30,"time":1601039656524,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"starting poller for default/sample-docker-config-json"}
{"level":20,"time":1601039656531,"pid":19,"hostname":"external-secrets-operator-kubernetes-external-secrets-7878nfjk2","msg":"next poll for default/sample-docker-config-json in 59973 ms"}
```
Did I do something wrong?

**Comment by gvfnix** [comment]
I sorted it out. The value of the secret should be plain JSON, not base64 encoded.
Maybe it is worth giving the example of setting the value for kubernetes.io/dockerconfigjson type.
