### ISSUE TITLE
Ungraceful handling incase secret missing content

### ISSUE THREAD

**Issue by asharma0930** [external-secrets/kubernetes-external-secrets#510]
We just had an incident in which the external-secret-manager went into a Pod crash looping problem when the secret contained no content. 
The secret looked like

```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  annotations:
    meta.helm.sh/release-name: <release-name>
    meta.helm.sh/release-namespace: <namespace>
  creationTimestamp: "2020-10-09T17:00:40Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: <es-name>
  namespace: <namespace>
  resourceVersion: "169083393"
  selfLink: /apis/kubernetes-client.io/v1/namespaces/<namespace>/externalsecrets/<es-name>
  uid: a77fcea9-4ae5-4160-ae8c-cb862c2eebd6
status:
  lastSync: "2020-10-12T19:04:11.406Z"
  observedGeneration: 1
  status: ERROR, Cannot read property 'template' of undefined
```

The error on the failing pods log -

```json
{"level":30,"time":1602521371393,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-d74844475-dp2n8","msg":"stopping poller for <namespace/<es-name>"}
TypeError: Cannot read property 'backendType' of undefined
    at Poller._poll (/app/lib/poller.js:131:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm info lifecycle kubernetes-external-secrets@4.1.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-external-secrets@4.1.0 start: `./bin/daemon.js`
npm ERR! Exit status 1
``` 
AND
```json
{"level":50,"time":1602521371209,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-d74844475-dp2n8","stack":"TypeError: Cannot read property 'template' of undefined\n    at Poller._createSecretManifest (/app/lib/poller.js:83:27)\n    at Poller._upsertKubernetesSecret (/app/lib/poller.js:152:39)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Poller._poll (/app/lib/poller.js:115:7)","type":"Error","msg":"failure while polling the secret <namespace>/<es-name>"}
``` 

Please let me know incase any more information is needed on the same. Thanks

**Comment by asharma0930** [comment]
Hello, Any update on this?
