### ISSUE TITLE
Secrets logged in clear text after parsing issue.

### ISSUE THREAD

**Issue by guxlightyear** [external-secrets/kubernetes-external-secrets#542]
While reviewing our application logs, I have noticed a line that looked like this (redacted for obvious reasons).

```
{"level":50,"time":1605105915359,"pid":17,"hostname":"platform-kubernetes-external-secrets-578c5b47f4-gh4db","stack":"TypeError: Cannot use 'in' operator to search for 'DATABASE_PORT' in DATABASE_HOST=<redacted> DATABASE_PORT=3306 DATABASE_USER=<redacted> DATABASE_PASSWORD=<redacted> DATABASE_NAME=<redacted> AWS_ACCESS_KEY_ID=<redacted> AWS_SECRET_ACCESS_KEY=<redacted> AWS_DEFAULT_REGION=<redacted> BUCKET_NAME=<redacted> TARGET_FOLDER=int\n    at /app/lib/backends/kv-backend.js:44:24\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Promise.all (index 1)\n    at async Promise.all (index 1)\n    at async SecretsManagerBackend.getSecretManifestData (/app/lib/backends/kv-backend.js:116:42)\n    at async Poller._createSecretManifest (/app/lib/poller.js:93:1
```

It looks as if when `external-secrets` has a problem parsing a JSON secret it exposes the whole secret as clear text in the logs, which depending on the situation can create a big security risk.

This issue is in the same area as https://github.com/godaddy/kubernetes-external-secrets/issues/97, so both could be dealt with at the same time:

```
# File lib/backends/kv-backend.js

      if (shouldParseValue) {
        let parsedValue
        try {
          parsedValue = JSON.parse(value)
        } catch (err) {
          this._logger.warn(`Failed to JSON.parse value for '${key}',` +
           ' please verify that your secret value is correctly formatted as JSON.' +
           ` To use plain text secret remove the 'property: ${property}'`)
          return
        }

        if (!(property in parsedValue)) {   // <-- the problem is on how the error is handled in this line
          throw new Error(`Could not find property ${property} in ${key}`)
        }
```

**Comment by guxlightyear** [comment]
Comment to remove "stale" label.
