### ISSUE TITLE
External Secrets are pods are crashing with 504 Gateway Time-out error. 

### ISSUE THREAD

**Issue by nvenkatapavan** [external-secrets/kubernetes-external-secrets#583]
**Issue Description:**
External Secrets sometime crashing if vault is having 504 Gateway Time-out errors, Is there a way we can ignore or handle the 504 Gateway time out errors instead of crashing pod or restarting it ? Please help on this issue on priority. 

**Error Logs:** 
```
2020-12-21T04:43:59.542176959Z {"level":30,"time":1608525839539,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"starting poller for myapp/ingress-tls"}
2020-12-21T04:45:53.497106766Z {"level":30,"time":1608525953496,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"running poll on the secret myapp/alertmanager-prometheus-operator-alertmanager"}
2020-12-21T04:45:53.501067453Z {"level":30,"time":1608525953498,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"running poll on the secret myapp/myregistrykey"}
2020-12-21T04:45:53.501100793Z {"level":30,"time":1608525953499,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"running poll on the secret myapp/myregistrykey"}
2020-12-21T04:45:53.761557904Z {"level":30,"time":1608525953761,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"upserting secret myapp/myregistrykey"}
2020-12-21T04:45:53.770094095Z {"level":30,"time":1608525953764,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"upserting secret myapp/myregistrykey"}
2020-12-21T04:45:53.770125566Z {"level":30,"time":1608525953769,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"upserting secret myapp/alertmanager-prometheus-operator-alertmanager"}
2020-12-21T04:45:53.842717447Z {"level":30,"time":1608525953842,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"stopping poller for myapp/myregistrykey"}
2020-12-21T04:45:53.845283776Z {"level":30,"time":1608525953842,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"starting poller for myapp/myregistrykey"}
2020-12-21T04:45:53.850305054Z {"level":30,"time":1608525953850,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"stopping poller for myapp/alertmanager-prometheus-operator-alertmanager"}
2020-12-21T04:45:53.853825524Z {"level":30,"time":1608525953850,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"starting poller for myapp/alertmanager-prometheus-operator-alertmanager"}
2020-12-21T04:45:53.865196047Z {"level":30,"time":1608525953864,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"stopping poller for myapp/myregistrykey"}
2020-12-21T04:45:53.867656404Z {"level":30,"time":1608525953865,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"starting poller for myapp/myregistrykey"}
2020-12-21T04:45:59.505677838Z {"level":30,"time":1608525959503,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"running poll on the secret myapp/ingress-tls"}
2020-12-21T04:45:59.859136026Z {"level":30,"time":1608525959858,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"upserting secret myapp/ingress-tls"}
2020-12-21T04:45:59.952738721Z {"level":30,"time":1608525959952,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"stopping poller for myapp/ingress-tls"}
2020-12-21T04:45:59.956405294Z {"level":30,"time":1608525959953,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-54489696db-5cdnj","msg":"starting poller for myapp/ingress-tls"}
2020-12-21T04:46:53.582087493Z ApiResponseError: Status 504
2020-12-21T04:46:53.582145255Z     at handleVaultResponse (/app/node_modules/node-vault/src/index.js:49:21)
2020-12-21T04:46:53.582159711Z     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2020-12-21T04:46:53.582169942Z   response: {
2020-12-21T04:46:53.582182156Z     statusCode: 504,
2020-12-21T04:46:53.582191983Z     body: '<html>\r\n' +
2020-12-21T04:46:53.582201809Z       '<head><title>504 Gateway Time-out</title></head>\r\n' +
2020-12-21T04:46:53.582212839Z       '<body>\r\n' +
2020-12-21T04:46:53.582224990Z       '<center><h1>504 Gateway Time-out</h1></center>\r\n' +
2020-12-21T04:46:53.582235845Z       '<hr><center>nginx</center>\r\n' +
2020-12-21T04:46:53.582246186Z       '</body>\r\n' +
2020-12-21T04:46:53.582266836Z       '</html>\r\n'
2020-12-21T04:46:53.582276594Z   }
2020-12-21T04:46:53.582287211Z }
2020-12-21T04:46:53.592986509Z npm info lifecycle kubernetes-external-secrets@4.0.0~start: Failed to exec start script
2020-12-21T04:46:53.598129154Z npm ERR! code ELIFECYCLE
2020-12-21T04:46:53.598188141Z npm ERR! errno 1
2020-12-21T04:46:53.604575638Z npm ERR! kubernetes-external-secrets@4.0.0 start: `./bin/daemon.js`
2020-12-21T04:46:53.604601449Z npm ERR! Exit status 1
2020-12-21T04:46:53.604713775Z npm ERR! 
2020-12-21T04:46:53.604772287Z npm ERR! Failed at the kubernetes-external-secrets@4.0.0 start script.
2020-12-21T04:46:53.604834641Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-12-21T04:46:53.610266443Z npm timing npm Completed in 239225ms
2020-12-21T04:46:53.610499529Z 
2020-12-21T04:46:53.610524852Z npm ERR! A complete log of this run can be found in:
2020-12-21T04:46:53.610603343Z npm ERR!     /home/node/.npm/_logs/2020-12-21T04_46_53_605Z-debug.log
```

**Comment by a5a5a9** [comment]
bump

**Comment by nvenkatapavan** [comment]
@Flydiverny Could you please help me on this issue please ?

**Comment by maloochpich** [comment]
@Flydiverny  we are facing the same issue. is there any way to debug this issue?

**Comment by Flydiverny** [comment]
All I can say is PRs welcome :) KES is a community effort and personally my time for KES is limited in general. Vault integration is all community contribution.
But yes I agree there should be better handling for this.
