### ISSUE TITLE
Issue with Google Secrets Manager while using Workload Identity 

### ISSUE THREAD

**Issue by tejaswinibussety** [external-secrets/kubernetes-external-secrets#591]
#### Issue Description:
External Secrets fail to fetch secrets from google secrets manager randomly. Please help on resolving this issue.

What I did,

Create k8s SA and Google Service Account with access to retrieve secrets.
```bash
export NAMESPACE=default
export CLUSTER_NAME=gcp-cluster
export PROJECT_ID=my-project
export SECRETS_MANAGER_PROJECT_ID=my-project
gcloud services enable secretmanager.googleapis.com --project $SECRETS_MANAGER_PROJECT_ID
kubectl create serviceaccount k8s-secret-manager -n $NAMESPACE
kubectl annotate sa k8s-secret-manager iam.gke.io/gcp-service-account=$CLUSTER_NAME-secret-manager@$SECRETS_MANAGER_PROJECT_ID.iam.gserviceaccount.com
gcloud iam service-accounts create $CLUSTER_NAME-secret-manager --project $SECRETS_MANAGER_PROJECT_ID
gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:$PROJECT_ID.svc.id.goog[$NAMESPACE/k8s-secret-manager]" \
  $CLUSTER_NAME-secret-manager@$SECRETS_MANAGER_PROJECT_ID.iam.gserviceaccount.com \
  --project $SECRETS_MANAGER_PROJECT_ID
gcloud projects add-iam-policy-binding $SECRETS_MANAGER_PROJECT_ID \
  --role roles/secretmanager.secretAccessor \
  --member "serviceAccount:$CLUSTER_NAME-secret-manager@$SECRETS_MANAGER_PROJECT_ID.iam.gserviceaccount.com" \
  --project $SECRETS_MANAGER_PROJECT_ID
```

I verified access to secrets manager as,
```bash
kubectl run --rm -it  --generator=run-pod/v1  --image google/cloud-sdk:slim  --serviceaccount k8s-secret-manager --namespace default  workload-identity-test
root@workload-identity-test:/# gcloud secrets versions access latest --secret="cp-dev-blip-secrets"
{
  "MYSQL_DB": "blip",
  "MYSQL_USERNAME": "root"
}
```

But, when I use the same service account for external secrets, it fails. I installed it via helm chart as,
```bash
helm install external-secrets external-secrets/kubernetes-external-secrets --set serviceAccount.create=False --set serviceAccount.name=k8s-secret-manager
```
Error I can see from logs on pod,

```bash
kubectl logs -f external-secrets-kubernetes-external-secrets-86d596767b-xc2g7

{"level":30,"time":1609251781470,"pid":18,"hostname":"external-secrets-kubernetes-external-secrets-86d596767b-xc2g7","msg":"upserting secret dev1/cp-secret-tls"}
{"level":30,"time":1609251781490,"pid":18,"hostname":"external-secrets-kubernetes-external-secrets-86d596767b-xc2g7","msg":"stopping poller for dev1/cp-secret-tls"}
{"level":30,"time":1609251781490,"pid":18,"hostname":"external-secrets-kubernetes-external-secrets-86d596767b-xc2g7","msg":"starting poller for dev1/cp-secret-tls"}
{"level":30,"time":1609251783114,"pid":18,"hostname":"external-secrets-kubernetes-external-secrets-86d596767b-xc2g7","msg":"running poll on the secret dev1/cp-automation-monitoring-secrets"}
{"level":30,"time":1609251783115,"pid":18,"hostname":"external-secrets-kubernetes-external-secrets-86d596767b-xc2g7","msg":"running poll on the secret dev1/amagicred"}
{"level":30,"time":1609251783116,"pid":18,"hostname":"external-secrets-kubernetes-external-secrets-86d596767b-xc2g7","msg":"running poll on the secret dev1/cp-automation-blip-secrets"}
{"level":30,"time":1609251783124,"pid":18,"hostname":"external-secrets-kubernetes-external-secrets-86d596767b-xc2g7","msg":"fetching secret property cp-docker-secrets with role: pods role in region undefined"}
{"level":30,"time":1609251783127,"pid":18,"hostname":"external-secrets-kubernetes-external-secrets-86d596767b-xc2g7","msg":"fetching secret property cp-dev-monitoring-secrets with role: pods role in region undefined"}
{"level":30,"time":1609251783127,"pid":18,"hostname":"external-secrets-kubernetes-external-secrets-86d596767b-xc2g7","msg":"fetching secret property cp-dev-blip-secrets with role: pods role in region undefined"}
{"level":50,"time":1609251783129,"pid":18,"hostname":"external-secrets-kubernetes-external-secrets-86d596767b-xc2g7","message":"Missing credentials in config","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Could not load credentials from any providers","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Missing credentials in config","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Could not load credentials from any providers","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Missing credentials in config","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Could not load credentials from any providers","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"EC2 Metadata roleName request returned error","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z"}}}}}},"stack":"CredentialsError: Missing credentials in config\n    at IncomingMessage.<anonymous> (/app/node_modules/aws-sdk/lib/util.js:895:34)\n    at IncomingMessage.emit (events.js:327:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:483:12)\n    at endReadableNT (_stream_readable.js:1220:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","type":"Error","msg":"failure while polling the secret dev1/amagicred"}
{"level":50,"time":1609251783130,"pid":18,"hostname":"external-secrets-kubernetes-external-secrets-86d596767b-xc2g7","message":"Missing credentials in config","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Could not load credentials from any providers","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Missing credentials in config","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Could not load credentials from any providers","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Missing credentials in config","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Could not load credentials from any providers","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"EC2 Metadata roleName request returned error","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z"}}}}}},"stack":"CredentialsError: Missing credentials in config\n    at IncomingMessage.<anonymous> (/app/node_modules/aws-sdk/lib/util.js:895:34)\n    at IncomingMessage.emit (events.js:327:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:483:12)\n    at endReadableNT (_stream_readable.js:1220:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","type":"Error","msg":"failure while polling the secret dev1/cp-automation-monitoring-secrets"}
{"level":50,"time":1609251783130,"pid":18,"hostname":"external-secrets-kubernetes-external-secrets-86d596767b-xc2g7","message":"Missing credentials in config","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Could not load credentials from any providers","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Missing credentials in config","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Could not load credentials from any providers","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Missing credentials in config","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"Could not load credentials from any providers","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z","code":"CredentialsError","originalError":{"message":"EC2 Metadata roleName request returned error","statusCode":404,"retryable":false,"time":"2020-12-29T14:23:03.129Z"}}}}}},"stack":"CredentialsError: Missing credentials in config\n    at IncomingMessage.<anonymous> (/app/node_modules/aws-sdk/lib/util.js:895:34)\n    at IncomingMessage.emit (events.js:327:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:483:12)\n    at endReadableNT (_stream_readable.js:1220:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","type":"Error","msg":"failure while polling the secret dev1/cp-automation-blip-secrets"}
```

I verified that the token of serviceAccount token mounted at /var/run/secrets/kubernetes.io/serviceaccount/token on both the pods (workload-identity-test, external-secrets-kubernetes-external-secrets-86d596767b-xc2g7) are same
```
$ kubectl describe po/external-secrets-kubernetes-external-secrets-86d596767b-xc2g7
.......
Volumes:
  k8s-secret-manager-token-wb25f:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  k8s-secret-manager-token-wb25f
    Optional:    false
QoS Class:       Burstable
.......
```

Please note that same process worked for me earlier, but not sure why it suddenly stops working.

**Comment by tejaswinibussety** [comment]
Hi all, 
Sorry my bad **backendType** I specified in my secret was incorrect. 

Closing this issue.
